/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jumpy.grof;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MapGUI extends javax.swing.JFrame {

    Map map;
    ArrayList<Point> point = new ArrayList<>();
    int colonyMin;
    
    Random rand = new Random();
    int[] place = null;
    int[] num = null;
    
    public MapGUI() {
        initComponents();
    }
    public MapGUI(Map map,Point[] points,int colonyMin) {
        initComponents();
        
        
        
        
        
        this.map=map;
        point = new ArrayList<Point>(Arrays.asList(points));
        this.colonyMin=colonyMin;
        place = new int[point.size()];
        this.num = new int[point.size()];
        
        
        System.out.println(map);
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
        p19.setVisible(false);
        p20.setVisible(false);
        
        
        
        //generate unique place
        for(int i=0;i<point.size();i++){
            num[i] = 1+rand.nextInt(20);
            
            for(int j=0;j<i;j++){
                if(num[i]==num[j])
                    i--;
            }
        }
        
        
        
        
        //set visible chosen places
        for(int i=1;i<=point.size();i++){
          
                String nombor = String.valueOf(i);
                
            
                switch(num[i-1]){
               
                case 1: p1.setName(nombor);
                        p1.setVisible(true); break;
                case 2: p2.setName(nombor);
                        p2.setVisible(true); break;
                case 3: p3.setName(nombor);
                        p3.setVisible(true); break;
                case 4: p4.setName(nombor);
                        p4.setVisible(true); break;
                case 5: p5.setName(nombor);
                        p5.setVisible(true); break;
                case 6: p6.setName(nombor);
                        p6.setVisible(true); break;
                case 7: p7.setName(nombor);
                        p7.setVisible(true); break;
                case 8: p8.setName(nombor);
                        p8.setVisible(true); break;
                case 9: p9.setName(nombor);
                        p9.setVisible(true); break;
                case 10: p10.setName(nombor);
                        p10.setVisible(true); break;
                case 11: p11.setName(nombor);
                        p11.setVisible(true); break;
                case 12: p12.setName(nombor);
                        p12.setVisible(true); break;
                case 13: p13.setName(nombor);
                        p13.setVisible(true); break;
                case 14: p14.setName(nombor);
                        p14.setVisible(true); break;
                case 15: p15.setName(nombor);
                        p15.setVisible(true); break;
                case 16: p16.setName(nombor);
                        p16.setVisible(true); break;
                case 17: p17.setName(nombor);
                        p17.setVisible(true); break;
                case 18: p18.setName(nombor);
                        p18.setVisible(true); break;
                case 19: p19.setName(nombor);
                        p19.setVisible(true); break;
                case 20: p20.setName(nombor);
                        p20.setVisible(true); break;
                }
                
           
            
            
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p15 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        p17 = new javax.swing.JLabel();
        p16 = new javax.swing.JLabel();
        p18 = new javax.swing.JLabel();
        p19 = new javax.swing.JLabel();
        p13 = new javax.swing.JLabel();
        p14 = new javax.swing.JLabel();
        p20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Map");

        p1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(0, 0, 0));
        p1.setText("1");
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
        });

        p2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(0, 0, 0));
        p2.setText("2");
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2MouseClicked(evt);
            }
        });

        p3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p3.setForeground(new java.awt.Color(0, 0, 0));
        p3.setText("3");
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3MouseClicked(evt);
            }
        });

        p4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p4.setForeground(new java.awt.Color(0, 0, 0));
        p4.setText("4");
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4MouseClicked(evt);
            }
        });

        p5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p5.setForeground(new java.awt.Color(0, 0, 0));
        p5.setText("5");
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
        });

        p15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p15.setForeground(new java.awt.Color(0, 0, 0));
        p15.setText("15");
        p15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p15MouseClicked(evt);
            }
        });

        p12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p12.setForeground(new java.awt.Color(0, 0, 0));
        p12.setText("12");
        p12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p12MouseClicked(evt);
            }
        });

        p6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p6.setForeground(new java.awt.Color(0, 0, 0));
        p6.setText("6");
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6MouseClicked(evt);
            }
        });

        p7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p7.setForeground(new java.awt.Color(0, 0, 0));
        p7.setText("7");
        p7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p7MouseClicked(evt);
            }
        });

        p10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p10.setForeground(new java.awt.Color(0, 0, 0));
        p10.setText("10");
        p10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p10MouseClicked(evt);
            }
        });

        p8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p8.setForeground(new java.awt.Color(0, 0, 0));
        p8.setText("8");
        p8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p8MouseClicked(evt);
            }
        });

        p9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p9.setForeground(new java.awt.Color(0, 0, 0));
        p9.setText("9");
        p9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p9MouseClicked(evt);
            }
        });

        p11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p11.setForeground(new java.awt.Color(0, 0, 0));
        p11.setText("11");
        p11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p11MouseClicked(evt);
            }
        });

        p17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p17.setForeground(new java.awt.Color(0, 0, 0));
        p17.setText("17");
        p17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p17MouseClicked(evt);
            }
        });

        p16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p16.setForeground(new java.awt.Color(0, 0, 0));
        p16.setText("16");
        p16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p16MouseClicked(evt);
            }
        });

        p18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p18.setForeground(new java.awt.Color(0, 0, 0));
        p18.setText("18");
        p18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p18MouseClicked(evt);
            }
        });

        p19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p19.setForeground(new java.awt.Color(0, 0, 0));
        p19.setText("19");
        p19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p19MouseClicked(evt);
            }
        });

        p13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p13.setForeground(new java.awt.Color(0, 0, 0));
        p13.setText("13");
        p13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p13MouseClicked(evt);
            }
        });

        p14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p14.setForeground(new java.awt.Color(0, 0, 0));
        p14.setText("14");
        p14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p14MouseClicked(evt);
            }
        });

        p20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p20.setForeground(new java.awt.Color(0, 0, 0));
        p20.setText("20");
        p20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(p13)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(p5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(p15)
                                .addGap(121, 121, 121)
                                .addComponent(p16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2)
                            .addComponent(p18))
                        .addGap(117, 117, 117)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p8)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p9)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p17)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p3)
                            .addComponent(p20))
                        .addGap(114, 114, 114))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(p14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(p1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(p6)
                        .addGap(89, 89, 89)
                        .addComponent(p7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(p12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p10)
                        .addGap(101, 101, 101)
                        .addComponent(p11)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(p3))
                            .addComponent(p2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(p8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(p1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(p7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(p9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p13)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p12)
                                    .addComponent(p4))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p11)
                                    .addComponent(p10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p17)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p14)
                                    .addComponent(p16))
                                .addGap(38, 38, 38)
                                .addComponent(p19)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(p20)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p15)
                                        .addGap(73, 73, 73)))
                                .addGap(59, 59, 59))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p5)
                        .addGap(92, 92, 92)
                        .addComponent(p18)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(p6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        String nombor = p1.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p1MouseClicked

    private void p2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseClicked
        String nombor = p2.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p2MouseClicked

    private void p3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseClicked
        String nombor = p3.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p3MouseClicked

    private void p4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseClicked
        String nombor = p4.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p4MouseClicked

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        String nombor = p5.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p5MouseClicked

    private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
        String nombor = p6.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p6MouseClicked

    private void p7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseClicked
        String nombor = p7.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p7MouseClicked

    private void p8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8MouseClicked
        String nombor = p8.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p8MouseClicked

    private void p9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9MouseClicked
        String nombor = p9.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p9MouseClicked

    private void p10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p10MouseClicked
        String nombor = p10.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p10MouseClicked

    private void p11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p11MouseClicked
        String nombor = p11.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p11MouseClicked

    private void p12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p12MouseClicked
        String nombor = p12.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p12MouseClicked

    private void p13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p13MouseClicked
        String nombor = p13.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p13MouseClicked

    private void p14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p14MouseClicked
        String nombor = p14.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p14MouseClicked

    private void p15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p15MouseClicked
        String nombor = p15.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p15MouseClicked

    private void p16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p16MouseClicked
        String nombor = p16.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p16MouseClicked

    private void p17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p17MouseClicked
        String nombor = p17.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p17MouseClicked

    private void p18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p18MouseClicked
        String nombor = p18.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p18MouseClicked

    private void p19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p19MouseClicked
        String nombor = p19.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p19MouseClicked

    private void p20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p20MouseClicked
        String nombor = p20.getName();
        int index = Integer.parseInt(nombor)-1;
        Point p = point.get(index);
        JOptionPane.showMessageDialog(this,p.toString());
    }//GEN-LAST:event_p20MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MapGUI().setVisible(true);
//            }
//        });
//    }
    
    public static boolean checkID(int id, Point[] points)
    {
        for(Point point : points)
            if(point == null) break;
            else if(point.getID() == id) return true;
        return false;
    }
    
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p12;
    private javax.swing.JLabel p13;
    private javax.swing.JLabel p14;
    private javax.swing.JLabel p15;
    private javax.swing.JLabel p16;
    private javax.swing.JLabel p17;
    private javax.swing.JLabel p18;
    private javax.swing.JLabel p19;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p20;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    // End of variables declaration//GEN-END:variables
}
