/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jumpy.grof;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author user
 */
public class User extends javax.swing.JFrame {

    
    Point[] points = null; 
    int colonyMin = -1;
    
    
    public User() {
        initComponents();
           
         
           
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numPoint = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        food = new javax.swing.JTextField();
        limitK = new javax.swing.JTextField();
        connect = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        colony = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        amaran = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Random Generated");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Click Here");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Insert the number of points (2-20)      :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 192, -1, -1));

        numPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPointActionPerformed(evt);
            }
        });
        jPanel1.add(numPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 194, 110, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID (0001 to 1000)                     : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 198, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Food  (5-25)                               :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 233, 164, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kangaroo Limit (5-12)            :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 262, 162, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Number of conection             :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 292, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 194, 91, -1));
        jPanel1.add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 230, 91, 22));

        limitK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitKActionPerformed(evt);
            }
        });
        jPanel1.add(limitK, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 258, 91, -1));

        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });
        jPanel1.add(connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 288, 91, -1));

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Food", "Kangaroo Limit", "No. of connections"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 326, 489, 250));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 288, 64, -1));

        jButton3.setText("Finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 88, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Number of kangaroo to be colonized :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 230, -1, -1));

        colony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colonyActionPerformed(evt);
            }
        });
        jPanel1.add(colony, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 232, 110, -1));

        amaran.setColumns(20);
        amaran.setRows(5);
        jScrollPane2.setViewportView(amaran);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 335, 130));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("JumpyGrof  ");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\output-onlinepngtools (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 130));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("The error(s) will be shown below :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPointActionPerformed

    }//GEN-LAST:event_numPointActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new MapGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectActionPerformed

    private void limitKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitKActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int count = 0;
        
        int[] data = new int[4];
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        //move textField to String
        String input_id = id.getText();
        String input_food = food.getText();
        String input_limitK = limitK.getText();
        String input_connect = connect.getText();
        
        
        //have blank
        if(input_id.equals("")||input_food.equals("")||input_limitK.equals("")||input_connect.equals(""))
            JOptionPane.showMessageDialog(this,"Please enter all data");count++;
            
            
        model.addRow(new Object[]{input_id, input_food, input_limitK, input_connect});
        
//        String input = numPoint.getText();
//        int bilanganPoint = Integer.parseInt(input);
// 
//        String[] dat = new String[4];
//        
//        for(int i=0;i<bilanganPoint;i++){
//            dat[0] = (String) model.getValueAt(0, 0);
//            dat[0] = (String) model.getValueAt(0, 0);
//            dat[0] = (String) model.getValueAt(0, 0);
//            dat[0] = (String) model.getValueAt(0, 0);
//            points[i] = new Point(data[0], data[1], data[2], data[3]);
//        }
        
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        amaran.setText("");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String input = numPoint.getText();
        int bilanganPoint = Integer.parseInt(input);
        int cek = 0;
        int problem = 0;
        String gp = colony.getText();
        
        colonyMin = Integer.parseInt(gp);
        String testExceedPoint = null;
        //cek error for bilangan point > input sebenar (ERROR)
//        testExceedPoint = (String) model.getValueAt(bilanganPoint, 0);
//          
//        
//        if(isNumber(testExceedPoint)){
//            problem++;System.out.println(problem);
//        }
        
        this.points = new Point[bilanganPoint];
        
        
        String[] dat = new String[4];
        int[] col = new int[4];
        int[] test = new int[bilanganPoint];
        
//        if(problem==0){
        for(int i=0;i<bilanganPoint;i++){
            dat[0] = (String) model.getValueAt(i, 0);
            dat[1] = (String) model.getValueAt(i, 1);
            dat[2] = (String) model.getValueAt(i, 2);
            dat[3] = (String) model.getValueAt(i, 3);
            
            col[0] = Integer.parseInt(dat[0]);
            col[1] = Integer.parseInt(dat[1]);
            col[2] = Integer.parseInt(dat[2]);
            col[3] = Integer.parseInt(dat[3]);
            
            if(col[0]<0 || col[0]>1000){
                amaran.setText(amaran.getText()+""+col[0]+ " id is not in range\n");cek++;}
            if(col[1]<5 || col[1]>25){
                amaran.setText(amaran.getText()+""+col[1]+ " food is not in range\n");cek++;}
            if(col[2]<5 || col[2]>12){
                amaran.setText(amaran.getText()+""+col[2]+ " kangaroo limit is not in range\n");cek++;}
            if(col[3]<1){
                amaran.setText(amaran.getText()+""+col[3]+ " connection is not in range\n");cek++;}
            
            points[i] = new Point(col[0], col[1], col[2], col[3]);
            
            }
        
        
        
            //cek unik id
        for(int a=0;a<bilanganPoint;a++){
                dat[0] = (String) model.getValueAt(a, 0);
                col[0] = Integer.parseInt(dat[0]);
                test[a] = col[0];
            for(int b=0;b<a;b++){
                dat[0] = (String) model.getValueAt(b, 0);
                col[0] = Integer.parseInt(dat[0]);
                test[b] = col[0];
                
                if(test[a]==test[b] && a!=b){
                    amaran.setText(amaran.getText()+""+test[a]+" id is not unik \n");cek++;
                }
            
            }    
        }    
        
        
        
        if(cek==0){
        Map map = new Map(points,  colonyMin);
        int[] num = null;
        new MapGUI(map,points,colonyMin).setVisible(true);
        this.setVisible(false);
        }
//        }else{
//            JOptionPane.showMessageDialog(this,"Change your numbet of points");
//        }
        
        
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void colonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colonyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colonyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }
    
    public static boolean checkID(int id, Point[] points)
    {
        for(Point point : points)
            if(point == null) break;
            else if(point.getID() == id) return true;
        return false;
    }
    
    public static boolean isNumber(String string) {return string.matches("^\\d+$");}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea amaran;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField colony;
    private javax.swing.JTextField connect;
    private javax.swing.JTextField food;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField limitK;
    private javax.swing.JTextField numPoint;
    // End of variables declaration//GEN-END:variables
}
